task/urls.py
from django.urls import path
from .views import (TasksListView,
                    TasksCreateView,
                    TasksUpdateView,
                    TagsListView,
                    TagsCreateView,
                    TagsUpdateView,
                    TagsDeleteView,
                    ToggleTaskCompleteView,)


app_name = 'task'


urlpatterns = [
    path('', TasksListView.as_view(), name='tasks_list'),
    path('task/<int:pk>/toggle/', ToggleTaskCompleteView.as_view(), name='tasks_toggle'),
    path('task/create/', TasksCreateView.as_view(), name='task_create'),
    path('task/<int:pk>/update/', TasksUpdateView.as_view(), name='task_update'),
    path('tags/', TagsListView.as_view(), name='tags_list'),
    path('tags/create/', TagsCreateView.as_view(), name='tags_create'),
    path('tags/<int:pk>/update/', TagsUpdateView.as_view(), name='tags_update'),
    path('tags/<int:pk>/delete/', TagsDeleteView.as_view(), name='tags_delete'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls', namespace='task')),
]

task/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", blank=True, related_name="tasks")

    def __str__(self):
        return self.title

class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

task/forms.py
from django import forms
from django.views import generic

from task.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'content', 'deadline', 'tags']
        widgets = {
            'deadline': forms.DateInput(attrs={'type': 'datetime-local'}),
            'tags': forms.CheckboxSelectMultiple(attrs={'size': 5}),
        }

task/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic, View
from django.views.generic import RedirectView

from task.forms import TaskForm
from task.models import Task, Tag


class TasksListView(generic.ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'task/task_list.html'

class ToggleTaskCompleteView(View):
    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=self.kwargs['pk'])
        task.complete = not task.complete
        task.save()
        return redirect('task:tasks_list')


class TasksCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'task/task_form.html'
    success_url = reverse_lazy('task:tasks_list')

class TasksUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'task/task_form.html'
    success_url = reverse_lazy('task:tasks_list')


class TagsListView(generic.ListView):
    model = Tag
    context_object_name = 'tags'
    template_name = 'task/tags_list.html'

class TagsCreateView(generic.CreateView):
    model = Tag
    fields = '__all__'
    template_name = 'task/tag_form.html'
    success_url = reverse_lazy('task:tags_list')

class TagsUpdateView(generic.UpdateView):
    model = Tag
    fields = '__all__'
    success_url = reverse_lazy('task:tags_list')

class TagsDeleteView(generic.DeleteView):
    model = Tag
    template_name = 'task/tag_delete_confirm.html'
    success_url = reverse_lazy('task:tags_list')

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}

  <title>{% block title %}TODO List{% endblock %}</title>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
        crossorigin="anonymous">
</head>
<body>

<div class="container mt-4">
  <div class="row">
    <!-- Sidebar -->
    <div class="col-md-3">
      {% block sidebar %}
        {% include 'includes/sidebar.html' %}
      {% endblock %}
    </div>

    <!-- Main content -->
    <div class="col-md-9">
      {% block content %}
      {% endblock %}
    </div>
  </div>

  <!-- Pagination -->
  <div class="row mt-4">
    <div class="col-12">
      {% block pagination %}
        {% include 'includes/pagination.html' %}
      {% endblock %}
    </div>
  </div>
</div>

<footer class="bg-light text-center text-muted py-3 fixed-bottom">
  <div class="container">
    &copy; {{ now.year }} My ToDo List. All rights reserved.
  </div>
</footer>


<!-- Bootstrap JS Bundle -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
        crossorigin="anonymous"></script>


</body>
</html>

templates/includes/pagination.html
{% if is_paginate %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
      <a href="?page={{ page_obj.previous_page_number }}{% if q %}&q={{ q }}{% endif %}" class="page-link">Prev</a>
    {% endif %}
    </li>

    <li class="page-item">
      <span>Page {{ page_obj.number }} of {{ page.obj.paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?={{ page_obj.next_page_number }}{% if q %}&q={{ q }}{% endif %}" class="page-link">Next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<div class="list-group">
  <a href="{% url 'task:tasks_list' %}" class="list-group-item list-group-item-action">Home page</a>
  <a href="{% url 'task:tags_list' %}" class="list-group-item list-group-item-action">Tags</a>

</div>

templates/task/tag_delete_confirm.html
{% extends 'base.html' %}

{% block title %}Delete Tag{% endblock %}

{% block content %}
<h1>Delete Tag</h1>
<p>Are you sure you want to delete the tag: <strong>{{ tag.name }}</strong>?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'task:tags_list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

templates/task/tag_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mt-2">
        {% if tag.id %}Update{% else %}Create{% endif %}
    </button>
    <a href="{% url 'task:tags_list' %}" class="btn btn-secondary mt-2">Cancel</a>
</form>
{% endblock %}

templates/task/tags_list.html
{% extends 'base.html' %}
{% block title %}
  Tag List
{% endblock %}

{% block content %}
  {% if tags %}
    <h1>
      Tags
      <a href="{% url 'task:tags_create' %}" class="btn btn-primary btn-sm">Add tag</a>
    </h1>

    <ul class="list-group">
      {% for tag in tags %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <span>{{ tag.name }}</span>
          <div>
            <a href="{% url 'task:tags_update' tag.id %}" class="btn btn-outline-primary btn-sm">Update</a>
            <a href="{% url 'task:tags_delete' tag.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
          </div>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h3>No tags in list</h3>
  {% endif %}
{% endblock %}

templates/task/task_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mt-2">
        {% if task.id %}Update{% else %}Create{% endif %}
    </button>
    <a href="{% url 'task:tasks_list' %}" class="btn btn-secondary mt-2">Cancel</a>
</form>
{% endblock %}

templates/task/task_list.html
{% extends 'base.html' %}
{% block title %}Home page{% endblock %}

{% block content %}
  {% if tasks %}
    <h1 class="mb-4">
      TODO List
      <a href="{% url 'task:task_create' %}" class="btn btn-primary btn-sm">Add task</a>
    </h1>

    {% for task in tasks %}
      <div class="mb-3 p-3 border rounded d-flex justify-content-between align-items-center">


        <div>
          <div class="d-flex align-items-center">
            <strong class="me-2">{{ task.title }}</strong>
            {% if task.complete %}
              <span class="badge bg-success me-2">Done</span>
            {% else %}
              <span class="badge bg-danger me-2">Not done</span>
            {% endif %}
          </div>

          <small class="text-muted">Created: {{ task.created_at }} | Deadline: {{ task.deadline }}</small><br>

          <div class="mt-1">
            Tags:
            {% for tag in task.tags.all %}
              <span class="badge bg-secondary me-1">
                {{ tag.name }}
                <a href="{% url 'task:tags_update' tag.id %}" class="text-white text-decoration-none ms-1">✏️</a>
                <a href="{% url 'task:tags_delete' tag.id %}" class="text-white text-decoration-none ms-1">🗑️</a>
              </span>
            {% empty %}
              <span>No tags</span>
            {% endfor %}
          </div>
        </div>

        <div class="text-end">
          <form method="post" action="{% url 'task:tasks_toggle' task.id %}">
            {% csrf_token %}
            {% if task.complete %}
              <button type="submit" class="btn btn-outline-success btn-sm">Undo</button>
            {% else %}
              <button type="submit" class="btn btn-outline-primary btn-sm">Complete</button>
            {% endif %}
          </form>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h3>No tasks in ToDo list</h3>
  {% endif %}
{% endblock %}